[workspace]
resolver = "3"

members = [
  "config-loader",
  "enum-traits-generics",
  "error-handling",
  "hello_rust",
  "module-5",
  "module-5-miniproject",
  "ownership", "rust_rest_api",
  "word_counter",
]
